//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Deck
{
    private List<Card> d;
    private List<Card> d
	{
		get;
		set;
	}

	private Random r
	{
		get;
		set;
	}

	public virtual {
		get;
		set;
	}

	public virtual Card Deal()
	{
        if (d.Count > 0)
        {
            int index = R.Next(0, d.Count);
            Card ans = d[index];
            d.RemoveAt(index);
            return ans;
        }
        else { throw new Exception(); }
    }

	public Deck()
	{
        d = new List<Card>();
        // generate all combinations of Suits and Counts:
        foreach (Suit s in Enum.GetValues(typeof(Suit)))
        {
            foreach (Count c in Enum.GetValues(typeof(Count)))
            {
                d.Add(new Card(c, s));
            }
        }
    }

}

